version: '3.7'
services:
  mongodb:
    image: mongo:3.6.17-xenial
    ports:
      - '27017:27017'
    volumes:
      - data-volume:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/user/src/app/src'
    hostname: restock-api
    ports:
      - '9000:9000'
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=docker
    command: >
      bash -c "
        yarn watch
      "

volumes:
  data-volume:
